version: "3.9"
services:
  back:
    build: ./back
    container_name: workmanager-back
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    environment:
      - TZ=Asia/Tokyo

  front:
    build: ./front
    container_name: workmanager-front
    ports:
      - "8501:8501"
    volumes:
      - ./front:/app
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - back